######################################################################
# Automatically generated by qmake (3.1) Sat Dec 10 16:31:25 2022
######################################################################

TEMPLATE = subdirs
TARGET = boost_asio
INCLUDEPATH += .

SUBDIRS += asio_client\
           asio_server
