######################################################################
# Automatically generated by qmake (3.1) Sat Dec 10 17:53:52 2022
######################################################################

TEMPLATE = subdirs

# Directories

SUBDIRS += chat_server\
           chat_client
